export const data = [
    {
        scanId: "SC-1300",
        patientId: "PT-001",
        patientName: "Joan Doe",
        date: "2024-12-10",
        time: "09:10",
        modelVersion: "v1.3.2",
        processedTimeMs: 812,
        probabilities: {
            Healthy: 0.982,
            LGG: 0.009,
            GBM: 0.005,
            Metastasis: 0.004,
        },
        prediction: "Healthy",
        confidence: 98.2,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1299",
        patientId: "PT-002",
        patientName: "Ahmed Ali",
        date: "2024-12-10",
        time: "08:42",
        modelVersion: "v1.3.2",
        processedTimeMs: 954,
        probabilities: {
            Healthy: 0.031,
            LGG: 0.947,
            GBM: 0.012,
            Metastasis: 0.01,
        },
        prediction: "LGG",
        confidence: 94.7,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1298",
        patientId: "PT-003",
        patientName: "Sara Mohamed",
        date: "2024-12-10",
        time: "08:05",
        modelVersion: "v1.3.2",
        processedTimeMs: 1031,
        probabilities: {
            Healthy: 0.022,
            LGG: 0.031,
            GBM: 0.901,
            Metastasis: 0.046,
        },
        prediction: "GBM",
        confidence: 90.1,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1297",
        patientId: "PT-004",
        patientName: "Omar Hassan",
        date: "2024-12-09",
        time: "17:30",
        modelVersion: "v1.3.2",
        processedTimeMs: 880,
        probabilities: {
            Healthy: 0.041,
            LGG: 0.052,
            GBM: 0.087,
            Metastasis: 0.82,
        },
        prediction: "Metastasis",
        confidence: 82.0,
        status: "review",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1296",
        patientId: "PT-005",
        patientName: "Fatma Khaled",
        date: "2024-12-09",
        time: "16:48",
        modelVersion: "v1.3.2",
        processedTimeMs: 760,
        probabilities: {
            Healthy: 0.971,
            LGG: 0.014,
            GBM: 0.008,
            Metastasis: 0.007,
        },
        prediction: "Healthy",
        confidence: 97.1,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1295",
        patientId: "PT-006",
        patientName: "Mostafa Adel",
        date: "2024-12-09",
        time: "15:50",
        modelVersion: "v1.3.2",
        processedTimeMs: 915,
        probabilities: {
            Healthy: 0.064,
            LGG: 0.892,
            GBM: 0.028,
            Metastasis: 0.016,
        },
        prediction: "LGG",
        confidence: 89.2,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1294",
        patientId: "PT-007",
        patientName: "Nour Samy",
        date: "2024-12-09",
        time: "14:33",
        modelVersion: "v1.3.2",
        processedTimeMs: 1004,
        probabilities: {
            Healthy: 0.018,
            LGG: 0.045,
            GBM: 0.914,
            Metastasis: 0.023,
        },
        prediction: "GBM",
        confidence: 91.4,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1293",
        patientId: "PT-008",
        patientName: "Youssef Tarek",
        date: "2024-12-09",
        time: "13:20",
        modelVersion: "v1.3.2",
        processedTimeMs: 840,
        probabilities: {
            Healthy: 0.963,
            LGG: 0.018,
            GBM: 0.011,
            Metastasis: 0.008,
        },
        prediction: "Healthy",
        confidence: 96.3,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1292",
        patientId: "PT-009",
        patientName: "Hana Ibrahim",
        date: "2024-12-09",
        time: "12:10",
        modelVersion: "v1.3.2",
        processedTimeMs: 987,
        probabilities: {
            Healthy: 0.051,
            LGG: 0.103,
            GBM: 0.086,
            Metastasis: 0.76,
        },
        prediction: "Metastasis",
        confidence: 76.0,
        status: "review",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1291",
        patientId: "PT-010",
        patientName: "Khaled Nabil",
        date: "2024-12-09",
        time: "11:35",
        modelVersion: "v1.3.2",
        processedTimeMs: 788,
        probabilities: {
            Healthy: 0.988,
            LGG: 0.006,
            GBM: 0.003,
            Metastasis: 0.003,
        },
        prediction: "Healthy",
        confidence: 98.8,
        status: "completed",
        radiologist: "Dr. Smith",
    },

    {
        scanId: "SC-1290",
        patientId: "PT-011",
        patientName: "Mariam Saad",
        date: "2024-12-08",
        time: "17:45",
        modelVersion: "v1.3.2",
        processedTimeMs: 902,
        probabilities: {
            Healthy: 0.038,
            LGG: 0.915,
            GBM: 0.027,
            Metastasis: 0.02,
        },
        prediction: "LGG",
        confidence: 91.5,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1289",
        patientId: "PT-012",
        patientName: "Salma Reda",
        date: "2024-12-08",
        time: "16:32",
        modelVersion: "v1.3.2",
        processedTimeMs: 1040,
        probabilities: {
            Healthy: 0.015,
            LGG: 0.026,
            GBM: 0.933,
            Metastasis: 0.026,
        },
        prediction: "GBM",
        confidence: 93.3,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1288",
        patientId: "PT-013",
        patientName: "Tamer Fathy",
        date: "2024-12-08",
        time: "15:10",
        modelVersion: "v1.3.2",
        processedTimeMs: 799,
        probabilities: {
            Healthy: 0.976,
            LGG: 0.011,
            GBM: 0.007,
            Metastasis: 0.006,
        },
        prediction: "Healthy",
        confidence: 97.6,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1287",
        patientId: "PT-014",
        patientName: "Rana Magdy",
        date: "2024-12-08",
        time: "14:00",
        modelVersion: "v1.3.2",
        processedTimeMs: 961,
        probabilities: {
            Healthy: 0.044,
            LGG: 0.085,
            GBM: 0.091,
            Metastasis: 0.78,
        },
        prediction: "Metastasis",
        confidence: 78.0,
        status: "review",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1286",
        patientId: "PT-015",
        patientName: "Hossam Eid",
        date: "2024-12-08",
        time: "12:55",
        modelVersion: "v1.3.2",
        processedTimeMs: 820,
        probabilities: {
            Healthy: 0.969,
            LGG: 0.015,
            GBM: 0.01,
            Metastasis: 0.006,
        },
        prediction: "Healthy",
        confidence: 96.9,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1285",
        patientId: "PT-016",
        patientName: "Dina Ashraf",
        date: "2024-12-08",
        time: "11:40",
        modelVersion: "v1.3.2",
        processedTimeMs: 930,
        probabilities: {
            Healthy: 0.058,
            LGG: 0.903,
            GBM: 0.021,
            Metastasis: 0.018,
        },
        prediction: "LGG",
        confidence: 90.3,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1284",
        patientId: "PT-017",
        patientName: "Amr Said",
        date: "2024-12-08",
        time: "10:15",
        modelVersion: "v1.3.2",
        processedTimeMs: 1018,
        probabilities: {
            Healthy: 0.023,
            LGG: 0.037,
            GBM: 0.912,
            Metastasis: 0.028,
        },
        prediction: "GBM",
        confidence: 91.2,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1283",
        patientId: "PT-018",
        patientName: "Aya Mahmoud",
        date: "2024-12-07",
        time: "16:30",
        modelVersion: "v1.3.2",
        processedTimeMs: 775,
        probabilities: {
            Healthy: 0.984,
            LGG: 0.008,
            GBM: 0.004,
            Metastasis: 0.004,
        },
        prediction: "Healthy",
        confidence: 98.4,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1282",
        patientId: "PT-019",
        patientName: "Mohamed Samir",
        date: "2024-12-07",
        time: "15:12",
        modelVersion: "v1.3.2",
        processedTimeMs: 944,
        probabilities: {
            Healthy: 0.067,
            LGG: 0.094,
            GBM: 0.089,
            Metastasis: 0.75,
        },
        prediction: "Metastasis",
        confidence: 75.0,
        status: "review",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1281",
        patientId: "PT-020",
        patientName: "Laila Yasser",
        date: "2024-12-07",
        time: "14:05",
        modelVersion: "v1.3.2",
        processedTimeMs: 806,
        probabilities: {
            Healthy: 0.975,
            LGG: 0.012,
            GBM: 0.007,
            Metastasis: 0.006,
        },
        prediction: "Healthy",
        confidence: 97.5,
        status: "completed",
        radiologist: "Dr. Smith",
    },
];
