export const data = [
    {
        scanId: "SC-1247",
        patientId: "Patient #4521",
        date: "2024-12-09",
        time: "14:32",
        prediction: "Healthy",
        confidence: 97.2,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1246",
        patientId: "Patient #4520",
        date: "2024-12-09",
        time: "13:15",
        prediction: "LGG",
        confidence: 94.8,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1245",
        patientId: "Patient #4519",
        date: "2024-12-09",
        time: "11:47",
        prediction: "GBM",
        confidence: 89.3,
        status: "review",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1244",
        patientId: "Patient #4518",
        date: "2024-12-08",
        time: "16:20",
        prediction: "Metastasis",
        confidence: 92.1,
        status: "completed",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1243",
        patientId: "Patient #4517",
        date: "2024-12-08",
        time: "15:05",
        prediction: "Healthy",
        confidence: 98.5,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1242",
        patientId: "Patient #4516",
        date: "2024-12-08",
        time: "13:40",
        prediction: "LGG",
        confidence: 91.7,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1241",
        patientId: "Patient #4515",
        date: "2024-12-07",
        time: "17:10",
        prediction: "GBM",
        confidence: 88.4,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1240",
        patientId: "Patient #4514",
        date: "2024-12-07",
        time: "15:55",
        prediction: "Healthy",
        confidence: 99.1,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1239",
        patientId: "Patient #4513",
        date: "2024-12-07",
        time: "14:22",
        prediction: "Metastasis",
        confidence: 90.6,
        status: "completed",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1238",
        patientId: "Patient #4512",
        date: "2024-12-06",
        time: "16:45",
        prediction: "LGG",
        confidence: 93.2,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1237",
        patientId: "Patient #4511",
        date: "2024-9-06",
        time: "15:10",
        prediction: "GBM",
        confidence: 87.9,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1236",
        patientId: "Patient #4510",
        date: "2024-9-06",
        time: "13:30",
        prediction: "Healthy",
        confidence: 96.8,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1235",
        patientId: "Patient #4509",
        date: "2024-9-05",
        time: "17:05",
        prediction: "Metastasis",
        confidence: 91.3,
        status: "completed",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1234",
        patientId: "Patient #4508",
        date: "2024-11-05",
        time: "15:40",
        prediction: "LGG",
        confidence: 92.6,
        status: "completed",
        radiologist: "Dr. Johnson",
    },
    {
        scanId: "SC-1233",
        patientId: "Patient #4507",
        date: "2024-11-05",
        time: "14:10",
        prediction: "Healthy",
        confidence: 98.9,
        status: "completed",
        radiologist: "Dr. Smith",
    },
    {
        scanId: "SC-1232",
        patientId: "Patient #4506",
        date: "2024-11-04",
        time: "16:50",
        prediction: "GBM",
        confidence: 86.5,
        status: "review",
        radiologist: "Dr. Brown",
    },
    {
        scanId: "SC-1231",
        patientId: "Patient #4505",
        date: "2024-10-05",
        time: "15:20",
        prediction: "Metastasis",
        confidence: 93.0,
        status: "completed",
        radiologist: "Dr. Williams",
    },
    {
        scanId: "SC-1230",
        patientId: "Patient #4504",
        date: "2024-10-04",
        time: "13:55",
        prediction: "Healthy",
        confidence: 97.6,
        status: "completed",
        radiologist: "Dr. Smith",
    },
];
